version: 0.0
os: windows
files:
  - source: \Database\bin\Debug\AdventureWorks.dacpac
    destination: C:\Builds\AdventureWorks
  - source: \install.bat
    destination: C:\Builds\AdventureWorks
  - source: \deployDb.ps1
    destination: C:\Builds\AdventureWorks
hooks:
  AfterInstall:
    - location: \install.bat
      timeout: 900
